In [2]:
import pandas as pd
import numpy as np
import re
# import tensorflow as tf
from sklearn.model_selection import train_test_split
# import tensorflow_hub as hub

In [11]:
train_data_twitter = pd.read_csv('../george_tweets.csv', encoding = 'utf-8')
train_data_twitter

      index  label alpha                                               text
0         0      1     a                    I love my mom and I love my dad
1         1      1     a  Just got my first ad for magnum condoms.. do t...
2         2      1     a                                         OOO KILLEM
3         3      1     a  The first time I heard the word ‘upshot’ I tho...
4         4      1     a  Guys wearing leggings should be socially accep...
...     ...    ...   ...                                                ...
2072   2072      1     a  @jaames_garcia03 i watched ... a track meet an...
2073   2073      1     a  @jaames_garcia03 lol. you cant do anything in ...
2074   2074      1     a                                             #NAME?
2075   2075      1     a                                             #NAME?
2076   2076      1     a   i am george. i am cooler than jackie. #DingDouLe

[2077 rows x 4 columns]

In [12]:
test_data_twitter = pd.read_csv('../george_tweets.csv', encoding = 'utf-8')
test_data_twitter

      index  label alpha                                               text
0         0      1     a                    I love my mom and I love my dad
1         1      1     a  Just got my first ad for magnum condoms.. do t...
2         2      1     a                                         OOO KILLEM
3         3      1     a  The first time I heard the word ‘upshot’ I tho...
4         4      1     a  Guys wearing leggings should be socially accep...
...     ...    ...   ...                                                ...
2072   2072      1     a  @jaames_garcia03 i watched ... a track meet an...
2073   2073      1     a  @jaames_garcia03 lol. you cant do anything in ...
2074   2074      1     a                                             #NAME?
2075   2075      1     a                                             #NAME?
2076   2076      1     a   i am george. i am cooler than jackie. #DingDouLe

[2077 rows x 4 columns]

In [13]:
def clean(tweet):
    # URLs
    tweet = re.sub(r"https?:\/\/t.co\/[A-Za-z0-9]+", "", tweet)
    
    # Emojis
    tweet = re.sub(r"<U\+[A-Za-z0-9]+>", "", tweet)
    
    # Contractions (ain't -> aint)
    tweet = re.sub(r"he’s", "he is", tweet)
    tweet = re.sub(r"there’s", "there is", tweet)
    tweet = re.sub(r"We’re", "We are", tweet)
    tweet = re.sub(r"That’s", "That is", tweet)
    tweet = re.sub(r"won’t", "will not", tweet)
    tweet = re.sub(r"they’re", "they are", tweet)
    tweet = re.sub(r"Can’t", "Cannot", tweet)
    tweet = re.sub(r"wasn’t", "was not", tweet)
    tweet = re.sub(r"don’t", "do not", tweet)
    tweet = re.sub(r"aren’t", "are not", tweet)
    tweet = re.sub(r"isn’t", "is not", tweet)
    tweet = re.sub(r"What’s", "What is", tweet)
    tweet = re.sub(r"haven’t", "have not", tweet)
    tweet = re.sub(r"hasn’t", "has not", tweet)
    tweet = re.sub(r"There’s", "There is", tweet)
    tweet = re.sub(r"He’s", "He is", tweet)
    tweet = re.sub(r"It’s", "It is", tweet)
    tweet = re.sub(r"You’re", "You are", tweet)
    tweet = re.sub(r"I’M", "I am", tweet)
    tweet = re.sub(r"shouldn’t", "should not", tweet)
    tweet = re.sub(r"wouldn’t", "would not", tweet)
    tweet = re.sub(r"i’m", "I am", tweet)
    tweet = re.sub(r"I’m", "I am", tweet)
    tweet = re.sub(r"I’m", "I am", tweet)
    tweet = re.sub(r"Isn’t", "is not", tweet)
    tweet = re.sub(r"Here’s", "Here is", tweet)
    tweet = re.sub(r"you’ve", "you have", tweet)
    tweet = re.sub(r"you’ve", "you have", tweet)
    tweet = re.sub(r"we’re", "we are", tweet)
    tweet = re.sub(r"what’s", "what is", tweet)
    tweet = re.sub(r"couldn’t", "could not", tweet)
    tweet = re.sub(r"we’ve", "we have", tweet)
    tweet = re.sub(r"it’s", "it is", tweet)
    tweet = re.sub(r"doesn’t", "does not", tweet)
    tweet = re.sub(r"It’s", "It is", tweet)
    tweet = re.sub(r"Here’s", "Here is", tweet)
    tweet = re.sub(r"who’s", "who is", tweet)
    tweet = re.sub(r"I’ve", "I have", tweet)
    tweet = re.sub(r"y’all", "you all", tweet)
    tweet = re.sub(r"can’t", "cannot", tweet)
    tweet = re.sub(r"would’ve", "would have", tweet)
    tweet = re.sub(r"it’ll", "it will", tweet)
    tweet = re.sub(r"we’ll", "we will", tweet)
    tweet = re.sub(r"wouldn’t", "would not", tweet)
    tweet = re.sub(r"We’ve", "We have", tweet)
    tweet = re.sub(r"he’ll", "he will", tweet)
    tweet = re.sub(r"Y’all", "You all", tweet)
    tweet = re.sub(r"Weren’t", "Were not", tweet)
    tweet = re.sub(r"Didn’t", "Did not", tweet)
    tweet = re.sub(r"they’ll", "they will", tweet)
    tweet = re.sub(r"they’d", "they would", tweet)
    tweet = re.sub(r"DON’T", "DO NOT", tweet)
    tweet = re.sub(r"That’s", "That is", tweet)
    tweet = re.sub(r"they’ve", "they have", tweet)
    tweet = re.sub(r"i’d", "I would", tweet)
    tweet = re.sub(r"should’ve", "should have", tweet)
    tweet = re.sub(r"You’re", "You are", tweet)
    tweet = re.sub(r"where’s", "where is", tweet)
    tweet = re.sub(r"Don’t", "Do not", tweet)
    tweet = re.sub(r"we’d", "we would", tweet)
    tweet = re.sub(r"i’ll", "I will", tweet)
    tweet = re.sub(r"weren’t", "were not", tweet)
    tweet = re.sub(r"They’re", "They are", tweet)
    tweet = re.sub(r"Can’t", "Cannot", tweet)
    tweet = re.sub(r"you’ll", "you will", tweet)
    tweet = re.sub(r"I’d", "I would", tweet)
    tweet = re.sub(r"let’s", "let us", tweet)
    tweet = re.sub(r"it’s", "it is", tweet)
    tweet = re.sub(r"can’t", "cannot", tweet)
    tweet = re.sub(r"don’t", "do not", tweet)
    tweet = re.sub(r"you’re", "you are", tweet)
    tweet = re.sub(r"i’ve", "I have", tweet)
    tweet = re.sub(r"that’s", "that is", tweet)
    tweet = re.sub(r"i’ll", "I will", tweet)
    tweet = re.sub(r"doesn’t", "does not", tweet)
    tweet = re.sub(r"i’d", "I would", tweet)
    tweet = re.sub(r"didn’t", "did not", tweet)
    tweet = re.sub(r"ain’t", "aint", tweet)
    tweet = re.sub(r"you’ll", "you will", tweet)
    tweet = re.sub(r"I’ve", "I have", tweet)
    tweet = re.sub(r"Don’t", "do not", tweet)
    tweet = re.sub(r"I’ll", "I will", tweet)
    tweet = re.sub(r"I’ll", "I will", tweet)
    tweet = re.sub(r"I’d", "I would", tweet)
    tweet = re.sub(r"Let’s", "Let us", tweet)
    tweet = re.sub(r"you’d", "You would", tweet)
    tweet = re.sub(r"It’s", "It is", tweet)
    tweet = re.sub(r"Ain’t", "aint", tweet)
    tweet = re.sub(r"Haven’t", "Have not", tweet)
    tweet = re.sub(r"Could’ve", "Could have", tweet)
    tweet = re.sub(r"youve", "you have", tweet)  
    tweet = re.sub(r"don’t", "do not", tweet) 
    
    # Words with punctuations and special characters
    punctuations = '@#!?+&*[]-%.:/();$=><|{}^,“”""' + "'`"
    for p in punctuations:
        tweet = tweet.replace(p, f' {p} ') 
    
    #removing new lines
    tweet = re.sub("\\n", " ", tweet)
    tweet = re.sub("\\r", " ", tweet)
    
    # MUST BE LAST
    # removing extra spaces
    tweet = re.sub(r" +", " ", tweet)
    
    return tweet

In [5]:
# x = 69696
# for i in range(0, 10):
#     temp = clean(train_data_twitter['text'][9])
#     print(temp)

clean(train_data_twitter['text'][8])

'Big flex , Kersh . On this day in 2013 , @ ClaytonKersh22 hit his first homer and tossed a complete game shutout against the Giants on Opening Day . '

In [16]:
train_data_twitter['text'] = train_data_twitter['text'].apply(lambda s : clean(s))
test_data_twitter['text'] = test_data_twitter['text'].apply(lambda s : clean(s))

In [17]:
train_data_twitter

,index,label,alpha,text,text_cleaned
0,0,1,a,I love my mom and I love my dad,I love my mom and I love my dad
1,1,1,a,Just got my first ad for magnum condoms . . do...,Just got my first ad for magnum condoms . . do...
2,2,1,a,OOO KILLEM,OOO KILLEM
3,3,1,a,The first time I heard the word ‘upshot’ I tho...,The first time I heard the word ‘upshot’ I tho...
4,4,1,a,Guys wearing leggings should be socially accep...,Guys wearing leggings should be socially accep...
...,...,...,...,...,...
2072,2072,1,a,@ jaames_garcia03 i watched . . . a track mee...,@ jaames_garcia03 i watched . . . a track mee...
2073,2073,1,a,@ jaames_garcia03 lol . you cant do anything ...,@ jaames_garcia03 lol . you cant do anything ...
2074,2074,1,a,# NAME ?,# NAME ?
2075,2075,1,a,# NAME ?,# NAME ?
2076,2076,1,a,i am george . i am cooler than jackie . # Ding...,i am george . i am cooler than jackie . # Ding...

In [8]:
train_data_twitter.to_csv('../../NLP-Twitter-FB/data/bert_train.tsv', index = False, header = True)

In [19]:
test_data_twitter.to_csv('../../NLP-Twitter-FB/data/george_tweet_test.csv', index = False, header = True)

In [103]:
train_data_twitter['text_cleaned'][8]

'Big flex , Kersh . \r \r On this day in 2013 , @ ClaytonKersh22 hit his first homer and tossed a complete game shutout against the Giants on Opening Day . '

In [6]:
train_data_twitter = pd.read_csv('../../NLP-Twitter-FB/pytorch-transformers-classification/data/bert_train.csv', encoding = 'utf-8')
train_data_twitter


test_data_twitter = pd.read_csv('../../NLP-Twitter-FB/pytorch-transformers-classification/data/bert_test.csv', encoding = 'utf-8')
test_data_twitter

      index  label alpha                                               text
0         0      1     a  Kawhi became suspicious . Cleared to play but ...
1         1      1     a  Shi * , I amma sleep good . Rather he stays or...
2         2      1     a  To get to an athlete , appeal to his toughness...
3         3      1     a  Should give you guys an anatomy chart . So you...
4         4      1     a  My only point is , KD should have gotten a 2nd...
...     ...    ...   ...                                                ...
5357   5425      0     a  the kung fu nuns of the hi amalayas break bric...
5358   5426      0     a  girl scouts of greater new yorks troop 6000 is...
5359   5427      0     a  they sell cookies , earn badges and , on their...
5360   5428      0     a   we changed our logo for # hashtag be sure to ...
5361   5429      0     a  chandro tomar , aka shooter dadi , is in her 8...

[5362 rows x 4 columns]

In [10]:
train_data_twitter.to_csv('../../pytorch-transformers-classification/data/train.tsv', index = False, header = True)
test_data_twitter.to_csv('../../pytorch-transformers-classification/data/dev.tsv', index = False, header = True)